### ISSUE TITLE
Shall Pospel check capitalized Words?

### ISSUE THREAD

**Issue by deronnax** [JulienPalard/pospell#3]
I see that pospell do check Capitalized words, and hence python-docs-fr's dict is filled with first names and surnames like *Farrugia*, *Catucci*, *Fredrik*, *Guido*, *Hettinger* & co.
Maybe pospell should not verify capitalized names?

**Comment by JulienPalard** [comment]
Pospell tries to be smart about checking or not capitalized words, see https://github.com/JulienPalard/pospell/blob/master/pospell.py#L92

```python
        # Strip capitalized words and accronyms in sentences
        r"(?<!\. |^)\b(\p{Letter}['’])?\b\p{Uppercase}\p{Letter}[\w.-]*\b",
        # Strip accronyms in the beginning of sentences
r"(?<=\. |^)\b(\p{Letter}['’])?\b\p{Uppercase}{2,}[\w-]*\b",
```

and tests : https://github.com/JulienPalard/pospell/blob/master/tests/test_pospell.py#L4

Basically pospell tries not *not* ignore words that are capitalized due to being the start of a sentence, and ignore all the others.

That's why in the french translation, the dict has in fact a very few subsets of names used in the documentation (only the ones found at the beginning of a sentence).

Should we ignore all capitalized words?

**Comment by deronnax** [comment]
Ah, I did not know, thank you very much.

Knowing what I do know, I would say that it's "good enough", I don't how we could do better.
